FORMAT: 1A

# Asylum Journey

# Group Home

## Home [/]

The home page.

+ Model

        {
            "_links": {
                "self": { "href": "/" },
                "services": { "href": "/services" },
                "providers": { "href": "/providers" },
                "stages": { "href": "/stages" },
                "categories": { "href": "/categories" },
                "service-users": { "href": "/service-users" },
                "issues": { "href": "/issues" }
            }
        }

### Read homepage [GET]
+ Response 200 (application/hal+json)

    [Home][]

# Group Services

## Service [/services/{id}]

+ Parameters
    + id (required, string, `1`) ... numeric `id` of the Service to perform action with. Has example value.

+ Model

        {
            "_links": {
                "self": { "href": "/services/1" }
            },
            "id": 1,
            "name": "My Service",
            "description": "This is a service",
            "dataMaintainer": "me",
            "endDate":"2018-01-01T00:00:00+0000",
             "_embedded": {
                "providers": [
                    {
                        "_links": {
                            "self": { "href": "/providers/1" }
                        },
                        "id": 1,
                        "name": "A provider",
                        "description": "This is a Provider",
                        "phone": "0114 2222222",
                        "email": "jeff@example.com",
                        "website":"http://www.provider.example.com",
                        "contactName":"Jeff Bdager",
                        "address": "Badger House",
                        "postcode": "S1 2NS"
                    },
                    {
                        "_links": {
                            "self": { "href": "/providers/2" }
                        },
                        "id": 2,
                        "name": "Another provider",
                        "description": "This is another Provider",
                        "phone": "0114 11111111",
                        "email": "barry@example.com",
                        "website":"http://www.another-provider.example.com",
                        "contactName":"Barry Bdager",
                        "address": "Badger Tower",
                        "postcode": "S11 8QD"
                    }
                ],
                "stages": [
                    {
                        "_links": {
                            "self": { "href": "/stages/1" }
                        },
                        "id": 1,
                        "name": "Arrival"
                    },
                    {
                        "_links": {
                            "self": { "href": "/stages/2" }
                        },
                        "id": 2,
                        "name": "Awaiting Decision"
                    }
                ],
                "categories": [
                    {
                        "_links": {
                            "self": { "href": "/categories/1" }
                        },
                        "id": 1,
                        "name": "Education",
                        "position": 8
                    }
                ],
                "serviceUsers": [
                    {
                        "_links": {
                            "self": { "href": "/service-users/2" }
                        },
                        "id": 2,
                        "name": "Families"
                    },
                    {
                        "_links": {
                            "self": { "href": "/service-users/3" }
                        },
                        "id": 3,
                        "name": "Children (under 18 years)"
                    }
                ],
                "issues": [
                    {
                        "_links": {
                            "self": { "href": "/issues/2" }
                        },
                        "id": 2,
                        "name": "Gap in provision"
                    }
                ]
            },
            "total": 8
        }

### Read a Service [GET]
+ Response 200 (application/hal+json)

    [Service][]

+ Response 404 (application/vnd.error+json)

        {
            "_links": {
                "about": { "href": "/services/9" }
            },
            "message": "Service not found"
        }

## Services Collection [/services]

### List All Services [GET]

+ Response 200 (application/hal+json)
    + Body

            {
                "_links": {
                    "self": { "href": "/services" }
                },
                "_embedded": {
                    "services": [
                        {
                            "_links": {
                                "self": { "href": "/services/1" }
                            },
                            "id": 1,
                            "name": "School Induction (Individual Schools)",
                            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse",
                            "dataMaintainer": "me",
                            "_embedded": {
                                "providers": [
                                    {
                                        "_links": {
                                            "self": { "href": "/providers/1" }
                                        },
                                        "id": 1,
                                        "name": "A provider",
                                        "description": "This is a Provider",
                                        "phone": "0114 2222222",
                                        "email": "jeff@example.com",
                                        "website":"http://www.provider.example.com",
                                        "contactName":"Jeff Bdager",
                                        "address": "Badger House",
                                        "postcode": "S1 2NS"
                                    },
                                    {
                                        "_links": {
                                            "self": { "href": "/providers/2" }
                                        },
                                        "id": 2,
                                        "name": "Another provider",
                                        "description": "This is another Provider",
                                        "phone": "0114 11111111",
                                        "email": "barry@example.com",
                                        "website":"http://www.another-provider.example.com",
                                        "contactName":"Barry Bdager",
                                        "address": "Badger Tower",
                                        "postcode": "S11 8QD"
                                    }
                                ],
                                "stages": [
                                    {
                                        "_links": {
                                            "self": { "href": "/stages/1" }
                                        },
                                        "id": 1,
                                        "name": "Arrival"
                                    },
                                    {
                                        "_links": {
                                            "self": { "href": "/stages/2" }
                                        },
                                        "id": 2,
                                        "name": "Awaiting Decision"
                                    },
                                    {
                                        "_links": {
                                            "self": { "href": "/stages/6" }
                                        },
                                        "id": 6,
                                        "name": "Gateway & Syrian resettlement programme"
                                    }
                                ],
                                "categories": [
                                    {
                                        "_links": {
                                            "self": { "href": "/categories/1" }
                                        },
                                        "id": 1,
                                        "name": "Education",
                                        "position": 2
                                    }
                                ],
                                "serviceUsers": [
                                    {
                                        "_links": {
                                            "self": { "href": "/service-users/2" }
                                        },
                                        "id": 2,
                                        "name": "Families"
                                    },
                                    {
                                        "_links": {
                                            "self": { "href": "/service-users/3" }
                                        },
                                        "id": 3,
                                        "name": "Children (under 18 years)"
                                    }
                                ]
                            },
                            "total": 8
                        },
                        {
                            "_links": {
                                "self": { "href": "/services/2" }
                            },
                            "id": 2,
                            "name": "Notice letter to leave G4S accommodation - G4S",
                            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse",
                            "dataMaintainer": "someone else",
                            "_embedded": {
                                "stages": [
                                    {
                                        "_links": {
                                            "self": { "href": "/stages/3" }
                                        },
                                        "id": 3,
                                        "name": "Positive Decision"
                                    }
                                ],
                                "categories": [
                                    {
                                        "_links": {
                                            "self": { "href": "/categories/3" }
                                        },
                                        "id": 3,
                                        "name": "Housing",
                                        "position": 2
                                    }
                                ],
                                "serviceUsers": [
                                    {
                                        "_links": {
                                            "self": { "href": "/service-users/1" }
                                        },
                                        "id": 1,
                                        "name": "All asylum seekers - no exclusions"
                                    }
                                ],
                                "issues": [
                                    {
                                        "_links": {
                                            "self": { "href": "/issues/3" }
                                        },
                                        "id": 3,
                                        "name": "Needs immediate action"
                                    }
                                ]
                            },
                            "total": 6
                        },
                        {
                            "_links": {
                                "self": { "href": "/services/3" }
                            },
                            "id": 3,
                            "name": "Registering for NHS Care (Mulberry Health Practice)",
                            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse",
                            "dataMaintainer": "me",
                            "endDate": "2018-01-01T00:00:00+0000",
                            "_embedded": {
                                "providers": [
                                    {
                                        "_links": {
                                            "self": { "href": "/providers/1" }
                                        },
                                        "id": 1,
                                        "name": "A provider",
                                        "description": "This is a Provider",
                                        "phone": "0114 2222222",
                                        "email": "jeff@example.com",
                                        "website":"http://www.provider.example.com",
                                        "contactName":"Jeff Bdager",
                                        "address": "Badger House",
                                        "postcode": "S1 2NS"
                                    }
                                ],
                                "stages": [
                                    {
                                        "_links": {
                                            "self": { "href": "/stages/1" }
                                        },
                                        "id": 1,
                                        "name": "Arrival"
                                    }
                                ],
                                "categories": [
                                    {
                                        "_links": {
                                            "self": { "href": "/categories/2" }
                                        },
                                        "id": 2,
                                        "name": "Health and social care",
                                        "position": 2
                                    }
                                ],
                                "serviceUsers": [
                                    {
                                        "_links": {
                                            "self": { "href": "/service-users/2" }
                                        },
                                        "id": 2,
                                        "name": "Families"
                                    },
                                    {
                                        "_links": {
                                            "self": { "href": "/service-users/3" }
                                        },
                                        "id": 3,
                                        "name": "Children (under 18 years)"
                                    }
                                ]
                            },
                            "total": 8
                        },
                        {
                            "_links": {
                                "self": { "href": "/services/4" }
                            },
                            "id": 4,
                            "name": "A finance service",
                            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse",
                            "dataMaintainer": "me",
                            "endDate": "2018-01-01T00:00:00+0000",
                            "_embedded": {
                                "providers": [
                                    {
                                        "_links": {
                                            "self": { "href": "/providers/1" }
                                        },
                                        "id": 1,
                                        "name": "A provider",
                                        "description": "This is a Provider",
                                        "phone": "0114 2222222",
                                        "email": "jeff@example.com",
                                        "website":"http://www.provider.example.com",
                                        "contactName":"Jeff Bdager",
                                        "address": "Badger House",
                                        "postcode": "S1 2NS"
                                    }
                                ],
                                "stages": [
                                    {
                                        "_links": {
                                            "self": { "href": "/stages/4" }
                                        },
                                        "id": 4,
                                        "name": "Negative Decision - Under Appeal"
                                    }
                                ],
                                "categories": [
                                    {
                                        "_links": {
                                            "self": { "href": "/categories/4" }
                                        },
                                        "id": 4,
                                        "name": "Finance (Personal)",
                                        "position": 2
                                    }
                                ],
                                "serviceUsers": [
                                    {
                                        "_links": {
                                            "self": { "href": "/service-users/2" }
                                        },
                                        "id": 2,
                                        "name": "Families"
                                    }
                                ]
                            },
                            "total": 8
                        },
                        {
                            "_links": {
                                "self": { "href": "/services/5" }
                            },
                            "id": 5,
                            "name": "Another finance service",
                            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse",
                            "dataMaintainer": "me",
                            "endDate": "2018-01-01T00:00:00+0000",
                            "_embedded": {
                                "providers": [
                                    {
                                        "_links": {
                                            "self": { "href": "/providers/1" }
                                        },
                                        "id": 1,
                                        "name": "A provider",
                                        "description": "This is a Provider",
                                        "phone": "0114 2222222",
                                        "email": "jeff@example.com",
                                        "website":"http://www.provider.example.com",
                                        "contactName":"Jeff Bdager",
                                        "address": "Badger House",
                                        "postcode": "S1 2NS"
                                    }
                                ],
                                "stages": [
                                    {
                                        "_links": {
                                            "self": { "href": "/stages/4" }
                                        },
                                        "id": 4,
                                        "name": "Negative Decision - Under Appeal"
                                    }
                                ],
                                "categories": [
                                    {
                                        "_links": {
                                            "self": { "href": "/categories/4" }
                                        },
                                        "id": 4,
                                        "name": "Finance (Personal)",
                                        "position": 2
                                    }
                                ],
                                "serviceUsers": [
                                    {
                                        "_links": {
                                            "self": { "href": "/service-users/2" }
                                        },
                                        "id": 2,
                                        "name": "Families"
                                    }
                                ]
                            },
                            "total": 8
                        },
                        {
                            "_links": {
                                "self": { "href": "/services/6" }
                            },
                            "id": 6,
                            "name": "Another service here",
                            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse",
                            "dataMaintainer": "me",
                            "_embedded": {
                                "stages": [
                                    {
                                        "_links": {
                                            "self": { "href": "/stages/5" }
                                        },
                                        "id": 5,
                                        "name": "Negative Decision - Destitute"
                                    }
                                ],
                                "categories": [
                                    {
                                        "_links": {
                                            "self": { "href": "/categories/5" }
                                        },
                                        "id": 5,
                                        "name": "Asylum process and legal advice",
                                        "position": 2
                                    }
                                ],
                                "serviceUsers": [
                                    {
                                        "_links": {
                                            "self": { "href": "/service-users/2" }
                                        },
                                        "id": 2,
                                        "name": "Families"
                                    }
                                ]
                            },
                            "total": 8
                        },
                        {
                            "_links": {
                                "self": { "href": "/services/7" }
                            },
                            "id": 7,
                            "name": "Initial School Education Support (SCC)",
                            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse",
                            "dataMaintainer": "me",
                            "_embedded": {
                                "stages": [
                                    {
                                        "_links": {
                                            "self": { "href": "/stages/1" }
                                        },
                                        "id": 1,
                                        "name": "Arrival"
                                    }
                                ],
                                "categories": [
                                    {
                                        "_links": {
                                            "self": { "href": "/categories/1" }
                                        },
                                        "id": 1,
                                        "name": "Education",
                                        "position": 2
                                    }
                                ],
                                "serviceUsers": [
                                    {
                                        "_links": {
                                            "self": { "href": "/service-users/2" }
                                        },
                                        "id": 2,
                                        "name": "Families"
                                    }
                                ]
                            },
                            "total": 8
                        }
                    ]
                },
                "total": 2
            }

# Group Providers

## Provider [/providers/{id}]

+ Parameters
    + id (required, string, `1`) ... numeric `id` of the Provider to perform action with. Has example value.

+ Model

        {
            "_links": {
                "self": { "href": "/providers/1" }
            },
            "id": 1,
            "name": "A provider",
            "description": "This is a Provider",
            "phone": "0114 2222222",
            "email": "jeff@example.com",
            "website":"http://www.provider.example.com",
            "contactName":"Jeff Bdager",
            "address": "Badger House",
            "postcode": "S1 2NS"
        }

### Read a Provider [GET]
+ Response 200 (application/hal+json)

    [Provider][]

+ Response 404 (application/vnd.error+json)

        {
            "_links": {
                "about": { "href": "/providers/9" }
            },
            "message": "provider not found"
        }

## Providers Collection [/providers]

### List All Providers [GET]

+ Response 200 (application/hal+json)
    + Body

            {
                "_links": {
                    "self": { "href": "/providers" }
                },
                "_embedded": {
                    "providers": [
                        {
                            "_links": {
                                "self": { "href": "/providers/1" }
                            },
                            "id": 1,
                            "name": "A provider",
                            "description": "This is a Provider",
                            "phone": "0114 2222222",
                            "email": "jeff@example.com",
                            "website":"http://www.provider.example.com",
                            "contactName":"Jeff Bdager",
                            "address": "Badger House",
                            "postcode": "S1 2NS"
                        },
                        {
                            "_links": {
                                "self": { "href": "/providers/2" }
                            },
                            "id": 2,
                            "name": "Another provider",
                            "description": "This is another Provider",
                            "phone": "0114 11111111",
                            "email": "barry@example.com",
                            "website":"http://www.another-provider.example.com",
                            "contactName":"Barry Bdager",
                            "address": "Badger Tower",
                            "postcode": "S11 8QD"
                        }
                    ]
                },
                "total": 2
            }

# Group Stages

## Stage [/stages/{id}]

+ Parameters
    + id (required, string, `1`) ... numeric `id` of the Stage to perform action with. Has example value.

+ Model

        {
            "_links": {
                "self": { "href": "/stages/1" }
            },
            "id": 1,
            "name": "Arrival"
        }

### Read a Stage [GET]
+ Response 200 (application/hal+json)

    [Stage][]

+ Response 404 (application/vnd.error+json)

        {
            "_links": {
                "about": { "href": "/stages/9" }
            },
            "message": "stage not found"
        }

## Stages Collection [/stages]

### List All Stages [GET]

+ Response 200 (application/hal+json)
    + Body

            {
                "_links": {
                    "self": { "href": "/stages" }
                },
                "_embedded": {
                    "stages": [
                        {
                            "_links": {
                                "self": { "href": "/stages/1" }
                            },
                            "id": 1,
                            "name": "Arrival"
                        },
                        {
                            "_links": {
                                "self": { "href": "/stages/2" }
                            },
                            "id": 2,
                            "name": "Awaiting Decision"
                        },
                        {
                            "_links": {
                                "self": { "href": "/stages/3" }
                            },
                            "id": 3,
                            "name": "Positive Decision"
                        },
                        {
                            "_links": {
                                "self": { "href": "/stages/4" }
                            },
                            "id": 4,
                            "name": "Negative Decision - Under Appeal"
                        },
                        {
                            "_links": {
                                "self": { "href": "/stages/5" }
                            },
                            "id": 5,
                            "name": "Negative Decision - Destitute"
                        },
                        {
                            "_links": {
                                "self": { "href": "/stages/6" }
                            },
                            "id": 6,
                            "name": "Gateway & Syrian resettlement programme"
                        },
                        {
                            "_links": {
                                "self": { "href": "/stages/7" }
                            },
                            "id": 7,
                            "name": "Leave to remain / no recourse"
                        }
                    ]
                },
                "total": 7
            }

# Group Categories

## Category [/categories/{id}]

+ Parameters
    + id (required, string, `1`) ... numeric `id` of the Category to perform action with. Has example value.

+ Model

        {
            "_links": {
                "self": { "href": "/categories/1" }
            },
            "id": 1,
            "name": "Education",
            "position": 2
        }

### Read a Category [GET]
+ Response 200 (application/hal+json)

    [Category][]

+ Response 404 (application/vnd.error+json)

        {
            "_links": {
                "about": { "href": "/categories/9" }
            },
            "message": "category not found"
        }

## Categories Collection [/categories]

### List All Categories [GET]

+ Response 200 (application/hal+json)
    + Body

            {
                "_links": {
                    "self": { "href": "/categories" }
                },
                "_embedded": {
                    "categories": [
                        {
                            "_links": {
                                "self": { "href": "/categories/1" }
                            },
                            "id": 1,
                            "name": "Education",
                            "position": 2
                        },
                        {
                            "_links": {
                                "self": { "href": "/categories/2" }
                            },
                            "id": 2,
                            "name": "Health and social care",
                            "position": 1
                        },
                        {
                            "_links": {
                                "self": { "href": "/categories/3" }
                            },
                            "id": 3,
                            "name": "Housing",
                            "position": 3
                        },
                        {
                            "_links": {
                                "self": { "href": "/categories/4" }
                            },
                            "id": 4,
                            "name": "Finance (Personal)",
                            "position": 4
                        },
                        {
                            "_links": {
                                "self": { "href": "/categories/5" }
                            },
                            "id": 5,
                            "name": "Asylum process and legal advice",
                            "position": 5
                        },
                        {
                            "_links": {
                                "self": { "href": "/categories/6" }
                            },
                            "id": 6,
                            "name": "Social/community (including volunteering)",
                            "position": 6
                        },
                        {
                            "_links": {
                                "self": { "href": "/categories/7" }
                            },
                            "id": 7,
                            "name": "Resources (Clothes,food etc)",
                            "position": 7
                        }
                    ]
                },
                "total": 7
            }

# Group Service Users

## ServiceUser [/service-users/{id}]

+ Parameters
    + id (required, string, `1`) ... numeric `id` of the Service User to perform action with. Has example value.

+ Model

        {
            "_links": {
                "self": { "href": "/service-users/1" }
            },
            "id": 1,
            "name": "All asylum seekers - no exclusions"
        }

### Read a ServiceUser [GET]
+ Response 200 (application/hal+json)

    [ServiceUser][]

+ Response 404 (application/vnd.error+json)

        {
            "_links": {
                "about": { "href": "/service-users/9" }
            },
            "message": "service user not found"
        }

## ServiceUsers Collection [/service-users]

### List All ServiceUsers [GET]

+ Response 200 (application/hal+json)
    + Body

            {
                "_links": {
                    "self": { "href": "/service-users" }
                },
                "_embedded": {
                    "service-users": [
                        {
                            "_links": {
                                "self": { "href": "/service-users/1" }
                            },
                            "id": 1,
                            "name": "All asylum seekers - no exclusions"
                        },
                        {
                            "_links": {
                                "self": { "href": "/service-users/2" }
                            },
                            "id": 2,
                            "name": "Families"
                        },
                        {
                            "_links": {
                                "self": { "href": "/service-users/3" }
                            },
                            "id": 3,
                            "name": "Children (under 18 years)"
                        },
                        {
                            "_links": {
                                "self": { "href": "/service-users/4" }
                            },
                            "id": 4,
                            "name": "Vulnerable adults"
                        },
                        {
                            "_links": {
                                "self": { "href": "/service-users/5" }
                            },
                            "id": 5,
                            "name": "Single men"
                        },
                        {
                            "_links": {
                                "self": { "href": "/service-users/6" }
                            },
                            "id": 6,
                            "name": "Single women"
                        }
                    ]
                },
                "total": 6
            }               
                        
# Group Issues

## Issue [/issues/{id}]

+ Parameters
    + id (required, string, `1`) ... numeric `id` of the Issue to perform action with. Has example value.

+ Model

        {
            "_links": {
                "self": { "href": "/issues/1" }
            },
            "id": 1,
            "name": "Service is under-resourced or needs further support"
        }

### Read an Issue [GET]
+ Response 200 (application/hal+json)

    [Issue][]
    
+ Response 404 (application/vnd.error+json)

        {
            "_links": {
                "about": { "href": "/issues/9" }
            },
            "message": "Issue not found"
        }
        
## Issues Collection [/issues]

### List All Issues [GET]

+ Response 200 (application/hal+json)
    + Body
    
            {
                "_links": {
                    "self": { "href": "/issues" }
                },
                "_embedded": {
                    "issues": [
                        {
                            "_links": {
                                "self": { "href": "/issues/1" }
                            },
                            "id": 1,
                            "name": "Service is under-resourced or needs further support"
                        },
                        {
                            "_links": {
                                "self": { "href": "/issues/2" }
                            },
                            "id": 2,
                            "name": "Gap in provision"
                        },
                        {
                            "_links": {
                                "self": { "href": "/issues/3" }
                            },
                            "id": 3,
                            "name": "Needs immediate action"
                        }
                    ]
                },
                "total": 3
            }                      
